version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /etc/nginx/html:/data/html
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /etc/nginx/log:/var/log/nginx
    network_mode: host
    privileged: true